### ISSUE TITLE
Unable to Import CA Policy containing "urn:user:registersecurityinfo" unless All Users are targeted

### ISSUE THREAD

**Issue by deanellerby** [nicolonsky/ModernWorkplaceConcierge#50]
When importing a CA policy containing the user action, and targeting at Groups rather than Users: All, the following error appears:

Error: Code: BadRequest Message: The server could not process the request because it is malformed or incorrect. Inner error: Message: 1012: 'applications' condition cannot include both 'includeApplications' and 'includeUserActions'/'includeProtectionLevels'. Please remove one of the conditions.

Applications is blank - 
"applications": {
      "includeApplications": [],
      "excludeApplications": [],
      "includeUserActions": [
        "urn:user:registersecurityinfo"
      ]
}

[CA - Base protection - Register security information- Require trusted device or location For internal users.zip](https://github.com/nicolonsky/ModernWorkplaceConcierge/files/4893479/CA.-.Base.protection.-.Register.security.information-.Require.trusted.device.or.location.For.internal.users.zip)

**Comment by nicolonsky** [comment]
Your CA policy looks strange/malformed because it does not contain any include assignments for users or groups. Tested it with the following two policies attached and worked without issues. Tested it on the tool and also Graph Explorer.
[Works.zip](https://github.com/nicolonsky/ModernWorkplaceConcierge/files/4895032/Works.zip)
