### ISSUE TITLE
Multiple Baseline Errors

### ISSUE THREAD

**Issue by mwalker1231** [nicolonsky/ModernWorkplaceConcierge#61]
Currently when attempting to add baseline conditional access policies to tenant most fail out.

I used "Device Trust with AADP1 and AADP2"

Attached are the output logs. Seems to be upset with the configured apps. I get similar errors when attempting to create policies via powershell.

[ModernWorkplaceConcierge.log](https://github.com/nicolonsky/ModernWorkplaceConcierge/files/5086177/ModernWorkplaceConcierge.log)

Thanks!

**Comment by nicolonsky** [comment]
Thanks for the hint. Microsoft updated the Graph API endpoint for Conditional Access policies which requires changes. I'll try to reflect them with an update.

**Comment by mwalker1231** [comment]
Thank you very much. I have loved using your tool for testing and learning.

**Comment by nicolonsky** [comment]
@mwalker1231 should be fixed since https://github.com/nicolonsky/ModernWorkplaceConcierge/commit/f90b0da6fc1524e3773955ba0a21f0d9a31392a5 although I removed 2 policy sets. Feel free to have a look at Alexander Filipin's awesome project for all policy sets: https://github.com/AlexFilipin/ConditionalAccess
