### ISSUE TITLE
Timeout while Importing Trello Tasks

### ISSUE THREAD

**Issue by tkagens** [nicolonsky/ModernWorkplaceConcierge#72]
Hello,

we have a problem with importing Trello tasks into Planner boards. Both via the web interface and via the self-hosted app in Azure the solution runs into a timeout after an irregular number of calls. Sometimes up to 1400 api calls are executed until a timeout occurs, sometimes this happens after only a handful of api calls. Error message from the logfile is the following:

> 2020-09-08T13:38:52.137Z Error: Code: timeout
> Message: The request timed out.

The following error message could be found in the ULS logs:

> {
>   "error": {
>     "code": "InvalidAuthenticationToken",
>     "message": "Access token is empty."
>     "innerError": {
>       "date": "2020-08-31T06:55:14",
>       "request-id": "902003e1-7d10-4982-a754-d48b361023b0"
>     }
>   }
> }

After a short time, the browser also displays an error message:

> 500 - The request timed out.
> The web server failed to respond within the specified time.

Is this problem known? We are looking forward to your feedback.

**Comment by nicolonsky** [comment]
Hi @tkagens first I supposed that the issue is tied to the app itself and how it handles token expiration but it's actually tied to the throttling limit on the Microsoft Graph side for Planner. Unfortunately, there's no limit published and this can vary. https://docs.microsoft.com/en-us/graph/throttling#tasks-and-plans-service-limits

But I can actually try to better handle the error and integrate this to the app. As a workaround, you could split your Trello export into smaller junks. The tasks are stored within the `cards` token of the JSON.

**Comment by tkagens** [comment]
Hi @nicolonsky,

many thanks for the quick feedback!!! 
We will test the way you have described and split the .json file accordingly.

**Comment by tkagens** [comment]
Hey!

Splitting the .json file worked for us, thanks!
