### ISSUE TITLE
" Deploy to Azure " - Error

### ISSUE THREAD

**Issue by mikki** [nicolonsky/ModernWorkplaceConcierge#78]
Thanks for this amazing app. I am having trouble with "Deploy to Azure". It throws error message, something like "We can’t connect to the server at deploy.azure.com."

Any help would be Appreciated 

Thanks

**Comment by BlueToxic** [comment]
Until the author updates the link on the main page you could try this workaround.
I used this documentation from Microsoft to generate the link:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button

Paste this link in your browser:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fnicolonsky%2FModernWorkplaceConcierge%2Fmaster%2Fazuredeploy.json

I had to remove the "/tree/master" part of the Repo Url.
Not sure why and I didn't bother finding out since it worked after I did this. First time I tried with the default URL and got an error during deployment.

Hope this helps

**Comment by tehmichael** [comment]
Thanks @BlueToxic, your workaround works pretty well!
